### PR TITLE
2.1.52+ cleanup and fixes

### LINKED ISSUE #96: Three bug in occlusion
Hello
I found Three bug in browser.
1- Close Menu doesn't function
2- In browser If you select card and active occlusion mode you can see the occlusions but you can't do anything (add or delete occlusion boxes , ...). So **if you want occlusion mode work in browser** you should first select card then select field which contain occlusions then active occlusion mode. 
3- When occlusion mode is active for a card in browser if you suddenly choose another card, the first card copies itself to second card.

I Hope i was able to elaborate issues properly.
- AnkiDesktop
- Windows
- 2.1.54

### PR DESCRIPTION
**Pull request by kleinerpirat**
Closes #96
and a bit of cleanup.

#95 suffered from two major issues:
1. https://github.com/ankitects/anki/issues/1980 - My PR had assumed a correct order. Switching to notetypes with differing # of fields would therefore cause Closet to insert occlusion code at wrong indices. The `fields` of `NoteEditor` API are ordered correctly.

2. Fields don't automatically update their state when Closet changes field contents. This could result in images getting copied to different notes' fields. I experimented a lot and settled on handling focus (forcing state updates) when loading notes.

## Caveat: Multiple Images
The way I fixed issue 2 doesn't allow for multiple images on a single IO note. In my eyes, the best approach would be to enable the IO editor only on the first image of the note. Another idea that came to mind was to hook into Anki's image handle (i.e. add the IO button there). Then users could easily decide which image should get the occlusions.

### CODE REVIEW

File: anki/web/editor.js [hunk 1]
```diff
@@ -69,27 +79,31 @@ document.addEventListener("keydown", (evt) => {
...
-
-        fieldElement.setAttribute("has-occlusion-style", "");
-    }
-})
+EditorField.lifecycle.onMount((field) => {
+    (async() => {
+        const fieldElement = await field.element;
+
+        if (!fieldElement.hasAttribute("has-occlusion-style")) {
+            const style = document.createElement("style");
```
Comment (hgiesel) [inline anki/web/editor.js:87]: Why was this change necessary (from async function to sync function with IIFE), did you encounter an issue here?

Comment (kleinerpirat) [reply anki/web/editor.js:87]: Loading a note with fewer fields caused an error, because async callbacks are not supported: https://github.com/ankitects/anki/issues/1959.

**Comment by hgiesel** [comment]
Tell me once you think this is ready for merging :)

**Comment by BEST8OY** [comment]
@kleinerpirat 
Please check this issue too.
I copied 2.1.52+fix branch of yours in closet addon directory to check if there is any issue.
I just faced an issue which prevent me from moving between cards with **up and down arrow keys on keyboard**.

File: anki/src/editor/__init__.py [hunk 2]
```diff
@@ -205,12 +200,19 @@ def on_cloze(editor) -> None:
     editor.web.eval(f'wrap("{prefix}", "{suffix}");')
 
 
+def clear_occlusion_mode(js, note, editor):
+    return f"EditorCloset.clearOcclusionMode().then(() => {{ {js} }}); "
+
+
+def refocus(editor):
+    editor.web.setFocus()
+    editor.web.eval("EditorCloset.refocusField(); ")
```
Comment (kleinerpirat) [inline anki/src/editor/__init__.py:209]: Thanks for testing @BEST8OY!

The bug you mentioned stems from line 208. Forcing focus on the editor seemed to be the only way to prevent following issue:

- start occlusion editor in the browser
- click on different note to load it
- the image + occlusion editor of former note is still displayed in the same field (i.e. the field content is not updated)

@hgiesel I'd be very interested if there was a less hacky way to solve this issue. I have experimented for days but didn't find a suitable solution other than setting focus.

Comment (BEST8OY) [reply anki/src/editor/__init__.py:209]: I'm not sure if i understood it properly.
Is the bug you mentioned in 3 steps to reproduce has been fixed by lines 208 and 209?
Because i followed your steps and the bug reproduced on my side.

1. I opened the browser.
2. Browser shows the first card. (obviously)
3. I start occlusion editor.
4. Select another card.
5. First card fields got copied into the second card.

If I don't want this problem to arise I have to add a step between steps number 1 and 2 which is selecting another card/ note other than the card that is showing by default by oppening browser.

Comment (hgiesel) [reply anki/src/editor/__init__.py:209]: I think there's a misunderstanding here, the issue still exists in this PR, and @kleinerpirat asks for my help

Comment (BEST8OY) [reply anki/src/editor/__init__.py:209]: @kleinerpirat 
I'm not sure what is happening either.
It's a gif of what is happening.
I figured the problem is in the first card you start occlusion editor. (not first card in the browser, rather the first card you start occlusion editor for)
After first duplication I undo the changes and it doesn't happen again.
anki_9tdT8taCQ6

Comment (BEST8OY) [reply anki/src/editor/__init__.py:209]: @kleinerpirat 
I have a good news.
I disabled all my addons and enabled Closet.
Duplication is no more.
Now I have to investigate which addon is interfering with Closet.
I think PR is good to go.
Some other addon is causing this problem.

**Comment by BEST8OY** [comment]
There is something I think worth mentioning.
When you active occlusion editor then select another card it add an enter in the end of the first card.
if you do it multiple time it just increase field length.
It is obvious in this gif.
https://i.imgur.com/nAVNHxk.gif

**Comment by BEST8OY** [comment]
A focusing issue appear in "add" window.
I made a gif for this too.
It happens when you leave focusing on add window.
In browser it does not happen.
https://i.imgur.com/gpgyX8V.gif

**Comment by kleinerpirat** [comment]
Thanks again for testing. I'm now convinced we can't simply hack around the core issue (which is fields not getting updated when they're modified programmatically). It's like a game of whack-a-mole.

In my eyes, this has to be fixed within Anki itself, if there is not already an official way to do it.

**Comment by kleinerpirat** [comment]
@hgiesel I think I got this bug-free now. I would have preferred to have some Anki API function like `upateFieldState`, but I managed to work around the issues with forced focus.

@BEST8OY if you got the time, I would be very grateful if you could test this one more time :)

**Comment by BEST8OY** [comment]
> @BEST8OY if you got the time, I would be very grateful if you could test this one more time :)
Everything seem to be fine on my side.
Thanks for fixing bugs so fast.

**Comment by BEST8OY** [comment]
@kleinerpirat 
One more bug.
Flagging card with Ctrl+Numbers is not possible in browser.
I hope i don't find more bugs so it could get release sooner.☹️

**Comment by kleinerpirat** [comment]
This is not a bug - Closet uses these shortcuts to switch its modes:
https://github.com/hgiesel/closet/blob/9c5fbb4081d757e163d029682eb5c19ef1947397/anki/src/editor/__init__.py#L151-L156

I just tested on 2.1.45 (older Closet version) and it looks like it has been this way ever since these shortcuts were introduced (https://github.com/hgiesel/closet/commit/d8f04a7a88505d89db27540a2f49f1f0f545d960).

**Comment by hgiesel** [comment]
> I would have preferred to have some Anki API function like `updateFieldState`

I don't quite understand the problem here. Updating the RichTextInput should trigger a mutation observer, updating the content in the db. What issue exactly are you encountering here?

**Comment by kleinerpirat** [comment]
Have you tried switching a note with the occlusion editor open on the current main? I think because of `preventResubscription` the field content will *stick* (seems to get "copied" over to the new note), even though I made sure to execute the callback before.

**Comment by kleinerpirat** [comment]
@hgiesel If you find the time, I suggest merging this in. It is a big improvement over the previous PR which is currently on AnkiWeb.

**Comment by AnKingMed** [comment]
@hgiesel can you merge this in so we at least have something on 2.1.50+?

**Review by hgiesel — APPROVED** [review]
